apiVersion: v1
kind: Service
metadata:
  name: {{ include "letters.fullname" . }}
  labels:
    {{- include "letters.labels" . | nindent 4 }}
  annotations:
    {{- range $key, $val := .Values.service.annotations }}
    {{ $key }}: {{ $val | quote }}
    {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- range .Values.service.ports }}
    - name: {{ .name }}
      protocol: {{ .protocol }}
      port: {{ .port }}
      targetPort: {{ .targetPort }}
    {{- end }}
  selector:
    {{- include "letters.selectorLabels" . | nindent 4 }}
