---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: github-trigger-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: "acme-prod"
spec:
  rules:
  - host: trigger.vexingworkshop.com
    http:
      paths:
      - backend:
          service:
            name: el-cluster-listener
            port:
              number: 8080
        path: /
        pathType: ImplementationSpecific
  tls:
    - hosts:
      - trigger.vexingworkshop.com
      secretName: vexing-tls
