apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: letters-deploy
spec:
  params:
    - name: repo-url
      type: string
      description: git repo to clone
    - name: branch
      type: string
      description: git branch to clone
    - name: image
      type: string
      description: name of the image to build
  workspaces:
    - name: source
      description: shared space containing source code
    - name: dockerconfig
      description: secret containing dockerconfigjson value
  tasks:
    - name: pull-source
      taskRef:
        name: git-clone
        bundle: gcr.io/tekton-releases/catalog/upstream/git-clone:0.4
      params:
        - name: url
          value: $(params.repo-url)
        - name: branch
          value: $(params.branch)
      workspaces:
        - name: output
          workspace: source
    - name: build-container
      taskRef:
        name: kaniko
        bundle: gcr.io/tekton-releases/catalog/upstream/kaniko:0.5
      runAfter:
        - pull-source
      params:
        - name: IMAGE
          value: $(params.image)
      workspaces:
        - name: source
          workspace: source
        - name: dockerconfig
          workspace: dockerconfig
