apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: letters-deploy
spec:
  params:
    - name: repo-url
      type: string
      description: git repo to clone
    - name: image
      type: string
      description: name of the image to build
    - name: chart_name
      type: string
      description: name of the helm chart to deploy
    - name: chart_version
      type: string
      description: version of the helm chart to deploy
    - name: chart_directory
      type: string
      description: directory containing the chart to deploy
    - name: release_namespace
      type: string
      description: namespace to deploy the chart
  workspaces:
    - name: source
      description: shared space containing source code
    - name: dockerconfig
      description: secret containing dockerconfigjson value
  tasks:
    - name: pull-source
      taskRef:
        name: git-clone
        bundle: gcr.io/tekton-releases/catalog/upstream/git-clone:0.4
      params:
        - name: url
          value: $(params.repo-url)
      workspaces:
        - name: output
          workspace: source
    - name: build-container
      taskRef:
        name: kaniko
        bundle: gcr.io/tekton-releases/catalog/upstream/kaniko:0.5
      runAfter:
        - pull-source
      params:
        - name: IMAGE
          value: $(params.image)
      workspaces:
        - name: source
          workspace: source
        - name: dockerconfig
          workspace: dockerconfig
    - name: deploy
      taskRef:
        name: helm-upgrade-from-source
        bundle: gcr.io/tekton-releases/catalog/upstream/helm-upgrade-from-source:0.3
      runAfter:
        - build-container
      params:
        - name: charts_dir
          value: $(params.chart_directory)
        - name: release_version
          value: $(params.chart_version)
        - name: release_name
          value: $(params.chart_name)
        - name: release_namespace
          value: $(params.release_namespace)
      workspaces:
        - name: source
          workspace: source
