---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: event-listener-role
rules:
  - apiGroups: [""]
    resources:
      - secrets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - triggers.tekton.dev
    resources:
      - eventlisteners
      - pipelineruns
      - triggers
      - triggertemplates
      - triggerbindings
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - tekton.dev
    resources:
      - pipelineruns
    verbs:
      - get
      - list
      - watch
      - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: event-listener-rolebinding
subjects:
  - kind: ServiceAccount
    name: {{ .Values.serviceAccount.listener }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: event-listener-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: interceptor-role
rules:
  - apiGroups:
      - triggers.tekton.dev
    resources:
      - clusterinterceptors
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: interceptor-rolebinding
subjects:
  - kind: ServiceAccount
    name: {{ .Values.serviceAccount.listener }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: interceptor-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pipeline-role
rules:
  - apiGroups: [""]
    resources:
      - pods
    verbs:
      - get
      - list
      - watch
      - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pipeline-rolebinding
subjects:
  - kind: ServiceAccount
    name: {{ .Values.serviceAccount.pipeline }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: pipeline-role
  apiGroup: rbac.authorization.k8s.io
