---
apiVersion: v1
kind: Secret
metadata:
  name: github-interceptor
data:
  interceptorSecret: "{{ .Values.github.interceptor.secret | b64enc }}"
---
apiVersion: v1
kind: Secret
metadata:
  name: github-docker-config
data:
  config.json: {{ .Values.dockerconfigjson }}
