apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: letters-build-pipeline
spec:
  params:
    - name: repo-url
      type: string
    - name: branch-name
      type: string
    - name: image
      type: string
  workspaces:
    - name: shared-data
  tasks:
    - name: fetch-repo
      taskRef:
        name: git-clone
      workspaces:
        - name: output
          workspace: shared-data
      params:
        - name: url
          value: $(params.repo-url)
        - name: revision
          value: $(params.branch-name)
    - name: kaniko
      taskRef:
        name: kaniko
      runAfter:
        - fetch-repo
      workspaces:
        - name: source
          workspace: shared-data
      params:
        - name: IMAGE
          value: $(params.image)
