chart:
  name: letters
  version: v0.1.0
  directory: charts/pipeline
release:
  namespace: letters
serviceAccount:
  pipeline: letters-pipeline
  listener: cluster-listener
ingress:
  host: trigger.vexingworkshop.com
  service: el-cluster-listener
  tlsSecretName: vexing-tls
